/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Clases.Clientes;
import Controlador.CtClientes;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mono-
 */
public class VistaClientes extends javax.swing.JFrame {

    CtClientes CtClientes;

    /**
     * Creates new form VistaProducto
     */
    public VistaClientes() {
        initComponents();
        this.CtClientes = new CtClientes();
    }

    public JButton getCerrar() {
        return Cerrar;
    }

    public void setCerrar(JButton Cerrar) {
        this.Cerrar = Cerrar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FCrear = new javax.swing.JFrame();
        JPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Crear2 = new javax.swing.JButton();
        Cerrar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbCreClie = new javax.swing.JTable();
        FConsulta = new javax.swing.JFrame();
        JPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Cerrar3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbConClie = new javax.swing.JTable();
        FActualizar = new javax.swing.JFrame();
        JPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Actualizar1 = new javax.swing.JButton();
        Cerrar4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TbActClie = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Crear = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();

        FCrear.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FCrear.setMinimumSize(new java.awt.Dimension(1140, 350));

        JPanel2.setBackground(new java.awt.Color(255, 255, 255));
        JPanel2.setMaximumSize(new java.awt.Dimension(732, 312));
        JPanel2.setMinimumSize(new java.awt.Dimension(732, 312));

        jPanel6.setBackground(new java.awt.Color(71, 168, 244));
        jPanel6.setMaximumSize(new java.awt.Dimension(171, 42));
        jPanel6.setMinimumSize(new java.awt.Dimension(171, 42));

        jLabel3.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Clientes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Crear2.setBackground(new java.awt.Color(71, 168, 244));
        Crear2.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Crear2.setText("Crear");
        Crear2.setToolTipText("");
        Crear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear2ActionPerformed(evt);
            }
        });

        Cerrar2.setBackground(new java.awt.Color(71, 168, 244));
        Cerrar2.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Cerrar2.setText("Cerrar");
        Cerrar2.setToolTipText("");
        Cerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar2ActionPerformed(evt);
            }
        });

        jScrollPane2.setMaximumSize(new java.awt.Dimension(452, 402));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(452, 402));

        TbCreClie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero ID", "Nombre", "Apellido", "Dirección", "Correo", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TbCreClie.setMaximumSize(new java.awt.Dimension(300, 20));
        TbCreClie.setMinimumSize(new java.awt.Dimension(300, 20));
        jScrollPane2.setViewportView(TbCreClie);
        if (TbCreClie.getColumnModel().getColumnCount() > 0) {
            TbCreClie.getColumnModel().getColumn(0).setHeaderValue("Numero ID");
            TbCreClie.getColumnModel().getColumn(1).setResizable(false);
            TbCreClie.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            TbCreClie.getColumnModel().getColumn(2).setHeaderValue("Apellido");
            TbCreClie.getColumnModel().getColumn(3).setHeaderValue("Dirección");
            TbCreClie.getColumnModel().getColumn(4).setHeaderValue("Correo");
            TbCreClie.getColumnModel().getColumn(5).setHeaderValue("Telefono");
        }

        javax.swing.GroupLayout JPanel2Layout = new javax.swing.GroupLayout(JPanel2);
        JPanel2.setLayout(JPanel2Layout);
        JPanel2Layout.setHorizontalGroup(
            JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(JPanel2Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(Crear2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        JPanel2Layout.setVerticalGroup(
            JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Crear2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FCrearLayout = new javax.swing.GroupLayout(FCrear.getContentPane());
        FCrear.getContentPane().setLayout(FCrearLayout);
        FCrearLayout.setHorizontalGroup(
            FCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FCrearLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        FCrearLayout.setVerticalGroup(
            FCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FCrearLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        FConsulta.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FConsulta.setMinimumSize(new java.awt.Dimension(1140, 350));

        JPanel3.setBackground(new java.awt.Color(255, 255, 255));
        JPanel3.setMaximumSize(new java.awt.Dimension(732, 312));
        JPanel3.setMinimumSize(new java.awt.Dimension(732, 312));

        jPanel7.setBackground(new java.awt.Color(71, 168, 244));
        jPanel7.setMaximumSize(new java.awt.Dimension(171, 42));
        jPanel7.setMinimumSize(new java.awt.Dimension(171, 42));

        jLabel4.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Clientes");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Cerrar3.setBackground(new java.awt.Color(71, 168, 244));
        Cerrar3.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Cerrar3.setText("Cerrar");
        Cerrar3.setToolTipText("");
        Cerrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar3ActionPerformed(evt);
            }
        });

        jScrollPane3.setMaximumSize(new java.awt.Dimension(452, 402));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(452, 402));

        TbConClie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero ID", "Nombre", "Apellido", "Dirección", "Correo", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TbConClie.setMaximumSize(new java.awt.Dimension(300, 20));
        TbConClie.setMinimumSize(new java.awt.Dimension(300, 20));
        jScrollPane3.setViewportView(TbConClie);

        javax.swing.GroupLayout JPanel3Layout = new javax.swing.GroupLayout(JPanel3);
        JPanel3.setLayout(JPanel3Layout);
        JPanel3Layout.setHorizontalGroup(
            JPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cerrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(502, 502, 502))
        );
        JPanel3Layout.setVerticalGroup(
            JPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Cerrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FConsultaLayout = new javax.swing.GroupLayout(FConsulta.getContentPane());
        FConsulta.getContentPane().setLayout(FConsultaLayout);
        FConsultaLayout.setHorizontalGroup(
            FConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FConsultaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        FConsultaLayout.setVerticalGroup(
            FConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FConsultaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        FActualizar.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FActualizar.setMinimumSize(new java.awt.Dimension(1140, 350));

        JPanel4.setBackground(new java.awt.Color(255, 255, 255));
        JPanel4.setMaximumSize(new java.awt.Dimension(732, 312));
        JPanel4.setMinimumSize(new java.awt.Dimension(732, 312));

        jPanel8.setBackground(new java.awt.Color(71, 168, 244));
        jPanel8.setMaximumSize(new java.awt.Dimension(171, 42));
        jPanel8.setMinimumSize(new java.awt.Dimension(171, 42));

        jLabel5.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Clientes");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Actualizar1.setBackground(new java.awt.Color(71, 168, 244));
        Actualizar1.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Actualizar1.setText("Actualizar");
        Actualizar1.setToolTipText("");
        Actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar1ActionPerformed(evt);
            }
        });

        Cerrar4.setBackground(new java.awt.Color(71, 168, 244));
        Cerrar4.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Cerrar4.setText("Cerrar");
        Cerrar4.setToolTipText("");
        Cerrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar4ActionPerformed(evt);
            }
        });

        jScrollPane4.setMaximumSize(new java.awt.Dimension(452, 402));
        jScrollPane4.setMinimumSize(new java.awt.Dimension(452, 402));

        TbActClie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        TbActClie.setMaximumSize(new java.awt.Dimension(300, 20));
        TbActClie.setMinimumSize(new java.awt.Dimension(300, 20));
        jScrollPane4.setViewportView(TbActClie);

        javax.swing.GroupLayout JPanel4Layout = new javax.swing.GroupLayout(JPanel4);
        JPanel4.setLayout(JPanel4Layout);
        JPanel4Layout.setHorizontalGroup(
            JPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(JPanel4Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(Actualizar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cerrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        JPanel4Layout.setVerticalGroup(
            JPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FActualizarLayout = new javax.swing.GroupLayout(FActualizar.getContentPane());
        FActualizar.getContentPane().setLayout(FActualizarLayout);
        FActualizarLayout.setHorizontalGroup(
            FActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FActualizarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        FActualizarLayout.setVerticalGroup(
            FActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FActualizarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 169));
        setMinimumSize(new java.awt.Dimension(750, 169));
        setPreferredSize(new java.awt.Dimension(750, 169));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(750, 169));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 169));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 169));

        jPanel2.setBackground(new java.awt.Color(71, 168, 244));
        jPanel2.setMaximumSize(new java.awt.Dimension(171, 42));
        jPanel2.setMinimumSize(new java.awt.Dimension(171, 42));

        jLabel1.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Crear.setBackground(new java.awt.Color(71, 168, 244));
        Crear.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Crear.setText("Crear");
        Crear.setToolTipText("");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        Actualizar.setBackground(new java.awt.Color(71, 168, 244));
        Actualizar.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setToolTipText("");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        Eliminar.setBackground(new java.awt.Color(71, 168, 244));
        Eliminar.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setToolTipText("");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Consultar.setBackground(new java.awt.Color(71, 168, 244));
        Consultar.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Consultar.setText("Consultar");
        Consultar.setToolTipText("");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Cerrar.setBackground(new java.awt.Color(71, 168, 244));
        Cerrar.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Cerrar.setText("Cerrar");
        Cerrar.setToolTipText("");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Actualizar)
                .addGap(20, 20, 20)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        FCrear.setVisible(true);
    }//GEN-LAST:event_CrearActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        String consulta = JOptionPane.showInputDialog("Introduzca el ID a eliminar");
        if (this.CtClientes.borrarClientes(consulta)) {
            JOptionPane.showMessageDialog(this, "Eliminacion Correcta");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        String consulta = JOptionPane.showInputDialog("Introduzca el ID a buscar");
        if (this.CtClientes.buscarClientes(consulta) == null) {
            JOptionPane.showMessageDialog(this, "No se pudo realizar la consulta");  
        } else {
            TbConClie.setModel(CtClientes.buscarClientes(consulta));
             JOptionPane.showMessageDialog(this, "Consulta Exitosa");
            FConsulta.setVisible(true);
        }
    }//GEN-LAST:event_ConsultarActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarActionPerformed

    private void Cerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar2ActionPerformed
        FCrear.setVisible(false);
    }//GEN-LAST:event_Cerrar2ActionPerformed

    private void Crear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear2ActionPerformed
        int fila = TbCreClie.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TbCreClie.getModel();
        String documentoCliente = (String) model.getValueAt(fila, 0);
        String nombreCliente = (String) model.getValueAt(fila, 1);
        String apellidoCliente = (String) model.getValueAt(fila, 2);
        String direccionCliente = (String) model.getValueAt(fila, 3);
        String correoCliente = (String) model.getValueAt(fila, 4);
        String telefonoCliente = (String) model.getValueAt(fila, 5);
        Clientes c = new Clientes(documentoCliente, nombreCliente, apellidoCliente, direccionCliente, correoCliente, telefonoCliente);
        if(this.CtClientes.crearClientes(c)){
            JOptionPane.showMessageDialog(this, "Registro agregado Correctamente");
        }else{
           JOptionPane.showMessageDialog(this, "No se pudo agregar el registro"); 
        }
        FCrear.setVisible(false);
        model.removeRow(fila);
        model.addRow(new Object[]{});
    }//GEN-LAST:event_Crear2ActionPerformed

    private void Cerrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar3ActionPerformed
        FConsulta.setVisible(false);
    }//GEN-LAST:event_Cerrar3ActionPerformed

    private void Actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar1ActionPerformed
        int fila = TbActClie.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TbActClie.getModel();
        int ID = Integer.parseInt((String) model.getValueAt(fila, 0));
        String documentoCliente = (String) model.getValueAt(fila, 1);
        String nombreCliente = (String) model.getValueAt(fila, 2);
        String apellidoCliente = (String) model.getValueAt(fila, 3);
        String direccionCliente = (String) model.getValueAt(fila, 4);
        String correoCliente = (String) model.getValueAt(fila, 5);
        String telefonoCliente = (String) model.getValueAt(fila, 6);
        Clientes c = new Clientes(ID, documentoCliente, nombreCliente, apellidoCliente, direccionCliente, correoCliente, telefonoCliente);
        if (this.CtClientes.actualizarClientes(c)) {
            FActualizar.setVisible(false);
            JOptionPane.showMessageDialog(this, "Registro Actualizado Correctamente");
        } else {
            FActualizar.setVisible(false);
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el registro");
        }
        
        String consulta = "";
        if (this.CtClientes.buscarClientes(consulta) == null) {
        } else {
            TbActClie.setModel(CtClientes.buscarClientes(consulta));
            FActualizar.setVisible(true);
        }
    }//GEN-LAST:event_Actualizar1ActionPerformed

    private void Cerrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar4ActionPerformed
        FActualizar.setVisible(false);
    }//GEN-LAST:event_Cerrar4ActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        String consulta = "";
        if (this.CtClientes.buscarClientes(consulta) == null) {
        } else {
            TbActClie.setModel(CtClientes.buscarClientes(consulta));
            FActualizar.setVisible(true);
        }
    }//GEN-LAST:event_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Actualizar1;
    private javax.swing.JButton Cerrar;
    private javax.swing.JButton Cerrar2;
    private javax.swing.JButton Cerrar3;
    private javax.swing.JButton Cerrar4;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Crear2;
    private javax.swing.JButton Eliminar;
    private javax.swing.JFrame FActualizar;
    private javax.swing.JFrame FConsulta;
    private javax.swing.JFrame FCrear;
    private javax.swing.JPanel JPanel2;
    private javax.swing.JPanel JPanel3;
    private javax.swing.JPanel JPanel4;
    private javax.swing.JTable TbActClie;
    private javax.swing.JTable TbConClie;
    private javax.swing.JTable TbCreClie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
