/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Clases.Proveedor;
import Controlador.CtProveedor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mono-
 */
public class VistaProveedor extends javax.swing.JFrame {

    CtProveedor CtProveedor;

    /**
     * Creates new form VistaProducto
     */
    public VistaProveedor() {
        initComponents();
        this.CtProveedor = new CtProveedor();
    }

    public JButton getCerrar() {
        return Cerrar;
    }

    public void setCerrar(JButton Cerrar) {
        this.Cerrar = Cerrar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FCrear = new javax.swing.JFrame();
        JPabel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Crear1 = new javax.swing.JButton();
        Cerrar1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TbCrePro = new javax.swing.JTable();
        FConsultar = new javax.swing.JFrame();
        JPabel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Cerrar2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        TbConPro = new javax.swing.JTable();
        FActualizar = new javax.swing.JFrame();
        JPabel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Cerrar3 = new javax.swing.JButton();
        Actualizar1 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        TbActPro = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Crear = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();

        FCrear.setMinimumSize(new java.awt.Dimension(1210, 350));
        FCrear.setResizable(false);

        JPabel2.setBackground(new java.awt.Color(255, 255, 255));
        JPabel2.setMaximumSize(new java.awt.Dimension(732, 312));
        JPabel2.setMinimumSize(new java.awt.Dimension(732, 312));

        jPanel6.setBackground(new java.awt.Color(71, 168, 244));
        jPanel6.setMaximumSize(new java.awt.Dimension(171, 42));
        jPanel6.setMinimumSize(new java.awt.Dimension(171, 42));

        jLabel3.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Proveedor");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Crear1.setBackground(new java.awt.Color(71, 168, 244));
        Crear1.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Crear1.setText("Crear");
        Crear1.setToolTipText("");
        Crear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear1ActionPerformed(evt);
            }
        });

        Cerrar1.setBackground(new java.awt.Color(71, 168, 244));
        Cerrar1.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Cerrar1.setText("Cerrar");
        Cerrar1.setToolTipText("");
        Cerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar1ActionPerformed(evt);
            }
        });

        jScrollPane5.setMaximumSize(new java.awt.Dimension(452, 402));
        jScrollPane5.setMinimumSize(new java.awt.Dimension(452, 402));

        TbCrePro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIT", "Razon Social", "Telefono", "Correo", "Representante", "Sitio Web", "ID Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TbCrePro.setMaximumSize(new java.awt.Dimension(300, 20));
        TbCrePro.setMinimumSize(new java.awt.Dimension(300, 20));
        jScrollPane5.setViewportView(TbCrePro);

        javax.swing.GroupLayout JPabel2Layout = new javax.swing.GroupLayout(JPabel2);
        JPabel2.setLayout(JPabel2Layout);
        JPabel2Layout.setHorizontalGroup(
            JPabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPabel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(JPabel2Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(Crear1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        JPabel2Layout.setVerticalGroup(
            JPabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPabel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(JPabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Crear1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout FCrearLayout = new javax.swing.GroupLayout(FCrear.getContentPane());
        FCrear.getContentPane().setLayout(FCrearLayout);
        FCrearLayout.setHorizontalGroup(
            FCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(FCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FCrearLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        FCrearLayout.setVerticalGroup(
            FCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
            .addGroup(FCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FCrearLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        FConsultar.setMinimumSize(new java.awt.Dimension(1210, 350));
        FConsultar.setResizable(false);

        JPabel3.setBackground(new java.awt.Color(255, 255, 255));
        JPabel3.setMaximumSize(new java.awt.Dimension(732, 312));
        JPabel3.setMinimumSize(new java.awt.Dimension(732, 312));

        jPanel7.setBackground(new java.awt.Color(71, 168, 244));
        jPanel7.setMaximumSize(new java.awt.Dimension(171, 42));
        jPanel7.setMinimumSize(new java.awt.Dimension(171, 42));

        jLabel4.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Proveedor");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Cerrar2.setBackground(new java.awt.Color(71, 168, 244));
        Cerrar2.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Cerrar2.setText("Cerrar");
        Cerrar2.setToolTipText("");
        Cerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar2ActionPerformed(evt);
            }
        });

        jScrollPane6.setMaximumSize(new java.awt.Dimension(452, 402));
        jScrollPane6.setMinimumSize(new java.awt.Dimension(452, 402));

        TbConPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        TbConPro.setMaximumSize(new java.awt.Dimension(300, 20));
        TbConPro.setMinimumSize(new java.awt.Dimension(300, 20));
        jScrollPane6.setViewportView(TbConPro);

        javax.swing.GroupLayout JPabel3Layout = new javax.swing.GroupLayout(JPabel3);
        JPabel3.setLayout(JPabel3Layout);
        JPabel3Layout.setHorizontalGroup(
            JPabel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPabel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPabel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(537, 537, 537))
        );
        JPabel3Layout.setVerticalGroup(
            JPabel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPabel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Cerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout FConsultarLayout = new javax.swing.GroupLayout(FConsultar.getContentPane());
        FConsultar.getContentPane().setLayout(FConsultarLayout);
        FConsultarLayout.setHorizontalGroup(
            FConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FConsultarLayout.createSequentialGroup()
                .addComponent(JPabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        FConsultarLayout.setVerticalGroup(
            FConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FConsultarLayout.createSequentialGroup()
                .addComponent(JPabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        FActualizar.setMinimumSize(new java.awt.Dimension(1210, 350));
        FActualizar.setResizable(false);

        JPabel4.setBackground(new java.awt.Color(255, 255, 255));
        JPabel4.setMaximumSize(new java.awt.Dimension(732, 312));
        JPabel4.setMinimumSize(new java.awt.Dimension(732, 312));

        jPanel8.setBackground(new java.awt.Color(71, 168, 244));
        jPanel8.setMaximumSize(new java.awt.Dimension(171, 42));
        jPanel8.setMinimumSize(new java.awt.Dimension(171, 42));

        jLabel5.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Proveedor");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Cerrar3.setBackground(new java.awt.Color(71, 168, 244));
        Cerrar3.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Cerrar3.setText("Cerrar");
        Cerrar3.setToolTipText("");
        Cerrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar3ActionPerformed(evt);
            }
        });

        Actualizar1.setBackground(new java.awt.Color(71, 168, 244));
        Actualizar1.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Actualizar1.setText("Actualizar");
        Actualizar1.setToolTipText("");
        Actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar1ActionPerformed(evt);
            }
        });

        jScrollPane7.setMaximumSize(new java.awt.Dimension(452, 402));
        jScrollPane7.setMinimumSize(new java.awt.Dimension(452, 402));

        TbActPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        TbActPro.setMaximumSize(new java.awt.Dimension(300, 20));
        TbActPro.setMinimumSize(new java.awt.Dimension(300, 20));
        jScrollPane7.setViewportView(TbActPro);

        javax.swing.GroupLayout JPabel4Layout = new javax.swing.GroupLayout(JPabel4);
        JPabel4.setLayout(JPabel4Layout);
        JPabel4Layout.setHorizontalGroup(
            JPabel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPabel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPabel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Actualizar1)
                .addGap(296, 296, 296)
                .addComponent(Cerrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
        );
        JPabel4Layout.setVerticalGroup(
            JPabel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPabel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(JPabel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout FActualizarLayout = new javax.swing.GroupLayout(FActualizar.getContentPane());
        FActualizar.getContentPane().setLayout(FActualizarLayout);
        FActualizarLayout.setHorizontalGroup(
            FActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FActualizarLayout.setVerticalGroup(
            FActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FActualizarLayout.createSequentialGroup()
                .addComponent(JPabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 169));
        setMinimumSize(new java.awt.Dimension(750, 169));
        setPreferredSize(new java.awt.Dimension(750, 169));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(750, 169));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 169));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 169));

        jPanel2.setBackground(new java.awt.Color(71, 168, 244));
        jPanel2.setMaximumSize(new java.awt.Dimension(171, 42));
        jPanel2.setMinimumSize(new java.awt.Dimension(171, 42));

        jLabel1.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proveedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Crear.setBackground(new java.awt.Color(71, 168, 244));
        Crear.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Crear.setText("Crear");
        Crear.setToolTipText("");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        Actualizar.setBackground(new java.awt.Color(71, 168, 244));
        Actualizar.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setToolTipText("");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        Eliminar.setBackground(new java.awt.Color(71, 168, 244));
        Eliminar.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setToolTipText("");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Consultar.setBackground(new java.awt.Color(71, 168, 244));
        Consultar.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Consultar.setText("Consultar");
        Consultar.setToolTipText("");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Cerrar.setBackground(new java.awt.Color(71, 168, 244));
        Cerrar.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        Cerrar.setText("Cerrar");
        Cerrar.setToolTipText("");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Actualizar)
                .addGap(20, 20, 20)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        FCrear.setVisible(true);
    }//GEN-LAST:event_CrearActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        String consulta = JOptionPane.showInputDialog("Introduzca el ID a eliminar");
        if (this.CtProveedor.borrarProveedor(consulta)) {
            JOptionPane.showMessageDialog(this, "Eliminacion Correcta");  
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        String consulta = JOptionPane.showInputDialog("Introduzca el ID a buscar");
        if (this.CtProveedor.buscarProveedor(consulta) == null) {
            JOptionPane.showMessageDialog(this, "No se pudo realizar la consulta");  
        } else {
            TbConPro.setModel(CtProveedor.buscarProveedor(consulta));
            JOptionPane.showMessageDialog(this, "Consulta Exitosa");
            FConsultar.setVisible(true);
        }
    }//GEN-LAST:event_ConsultarActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarActionPerformed

    private void Crear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear1ActionPerformed
        int fila = TbCrePro.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TbCrePro.getModel();
        String numeroNit = (String) model.getValueAt(fila, 0);
        String razonSocial = (String) model.getValueAt(fila, 1);
        String telefono = (String) model.getValueAt(fila, 2);
        String correoElectronico = (String) model.getValueAt(fila, 3);
        String representanteLegal = (String) model.getValueAt(fila, 4);
        String sitioWeb = (String) model.getValueAt(fila, 5);
        int Direcciones_idDireccion = (int) model.getValueAt(fila, 6);
        Proveedor p = new Proveedor(numeroNit, razonSocial, telefono, correoElectronico, representanteLegal, sitioWeb, Direcciones_idDireccion);
        if (this.CtProveedor.crearProveedor(p)) {
            JOptionPane.showMessageDialog(this, "Registro agregado Correctamente");
        }else{
           JOptionPane.showMessageDialog(this, "No se pudo agregar el registro"); 
        }
        FCrear.setVisible(false);
        model.removeRow(fila);
        model.addRow(new Object[]{});
    }//GEN-LAST:event_Crear1ActionPerformed

    private void Cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar1ActionPerformed
        FCrear.setVisible(false);
    }//GEN-LAST:event_Cerrar1ActionPerformed

    private void Cerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar2ActionPerformed
        FConsultar.setVisible(false);
    }//GEN-LAST:event_Cerrar2ActionPerformed

    private void Cerrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar3ActionPerformed
        FActualizar.setVisible(false);
    }//GEN-LAST:event_Cerrar3ActionPerformed

    private void Actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar1ActionPerformed
        int fila = TbActPro.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TbActPro.getModel();
        int ID = Integer.parseInt((String) model.getValueAt(fila, 0));
        String numeroNit = (String) model.getValueAt(fila, 1);
        String razonSocial = (String) model.getValueAt(fila, 2);
        String telefono = (String) model.getValueAt(fila, 3);
        String correoElectronico = (String) model.getValueAt(fila, 4);
        String representanteLegal = (String) model.getValueAt(fila, 5);
        String sitioWeb = (String) model.getValueAt(fila, 6);
        int Direcciones_idDireccion = Integer.parseInt((String) model.getValueAt(fila, 7));
        Proveedor p = new Proveedor(ID, numeroNit, razonSocial, telefono, correoElectronico, representanteLegal, sitioWeb, Direcciones_idDireccion);
        if (this.CtProveedor.actualizarProveedor(p)) {
            FActualizar.setVisible(false);
            JOptionPane.showMessageDialog(this, "Registro Actualizado Correctamente");
        } else {
            FActualizar.setVisible(false);
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el registro");
        }
        
         String consulta = "";
        if (this.CtProveedor.buscarProveedor(consulta) == null) {
        } else {
            TbActPro.setModel(CtProveedor.buscarProveedor(consulta));
            FActualizar.setVisible(true);
        }
        
    }//GEN-LAST:event_Actualizar1ActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        String consulta = "";
        if (this.CtProveedor.buscarProveedor(consulta) == null) {
        } else {
            TbActPro.setModel(CtProveedor.buscarProveedor(consulta));
            FActualizar.setVisible(true);
        }
    }//GEN-LAST:event_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Actualizar1;
    private javax.swing.JButton Cerrar;
    private javax.swing.JButton Cerrar1;
    private javax.swing.JButton Cerrar2;
    private javax.swing.JButton Cerrar3;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Crear1;
    private javax.swing.JButton Eliminar;
    private javax.swing.JFrame FActualizar;
    private javax.swing.JFrame FConsultar;
    private javax.swing.JFrame FCrear;
    private javax.swing.JPanel JPabel2;
    private javax.swing.JPanel JPabel3;
    private javax.swing.JPanel JPabel4;
    private javax.swing.JTable TbActPro;
    private javax.swing.JTable TbConPro;
    private javax.swing.JTable TbCrePro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
